### ISSUE TITLE
如果启动时使用rc指定config，而config文件不是在程序所在目录，那direct和proxy两个文件是使用的哪个目录下的

### ISSUE THREAD

**Issue by uuudbx** [renzhn/MEOW#10]
用rc指定目录后不知道读取的是哪个目录下的direct和proxy。是rc指定的config所在目录，还是exe程序所在目录。windows环境下。

**Comment by renzhn** [comment]
https://github.com/renzhn/MEOW/blob/master/config.go#L85 应该是rc所在的文件夹

**Comment by uuudbx** [comment]
明白。原先两个目录下都放了
