### ISSUE TITLE
你好作者，能不能增加N+账号同时连接的功能

### ISSUE THREAD

**Issue by lsnmx** [renzhn/MEOW#11]
https://github.com/librehat/shadowsocks-qt5 就比如QT5这样能够同时连接N+个账号和每个账号都不同的监听端口，因为真的是需要这个功能，某些网站需要固定IP啊，现在使用loadBalance = latency后，就无法固定IP了，请支持一下同时连接N+个账号，谢谢了！

现在配置如下！
listen = http://127.0.0.1:9999
listen = http://127.0.0.1:4422

loadBalance = latency

judgeByIP = false

proxy = ss://rc4-md5~~~

proxy = ss://rc4-md5~~~

**Comment by renzhn** [comment]
暂时没时间增加~
