### ISSUE TITLE
没有在直连列表的网站，特别是IP地址的URL（如：土豆视频上传）会出现不能慢速的现象

### ISSUE THREAD

**Issue by 5sq** [renzhn/MEOW#12]
在上传带宽100兆的情况下上传只有700k左右，但比COW 好点，COW只有100K左右。

出现不能慢速的现象时：

[<<<<<] 2015/08/16 00:14:15 POST 101.227.9.42:80/uploading?tk=168516794_23779694
9&iid=237796949&si=3&ver=html5&fs=48014652&bid=29 200 OK
[<<<<<] 2015/08/16 00:14:15 GET 101.227.9.42:80/prog?tk=168516794_237796949&iid=
237796949&si=3&ver=html5&fs=48014652&bid=10&r=1439655255139 200 OK
[<<<<<] 2015/08/16 00:14:15 GET 101.227.9.42:80/prog?tk=168516794_237796949&iid=
237796949&si=3&ver=html5&fs=48014652&bid=30&r=1439655255146 200 OK
[<<<<<] 2015/08/16 00:14:15 OPTIONS 101.227.9.42:80/uploading?tk=168516794_23779
6949&iid=237796949&si=3&ver=html5&fs=48014652&bid=10 200 OK

**Comment by renzhn** [comment]
不能慢速的现象？

**Comment by 5sq** [comment]
是的
