### ISSUE TITLE
建议：增加前置代理监听端口和前置代理选项

### ISSUE THREAD

**Issue by 5sq** [renzhn/MEOW#14]
建议：增加前置代理监听端口和前置代理选项

现在Meow也可以做前置代理，但做前置代理后Meow的更多功能就失去了（也许没有很好的理解作者软件的使用方法）。因此建议能否单独开辟个前置代理服务器监听地址，让Pre-Agent端口监听的数据直接通往指定前置代理。同时，二级代理如：goproxy、tor任然可以在二级代理列表中，这样就可以更好的发挥Meow的作用。

# 代理服务器监听地址
#
#	listen = protocol://[optional@]server_address:server_port

#前置代理服务器监听地址

#	Pre-Agent = protocol://[optional@]server_address:server_port

# 指定前置代理(只能指定1个)

#	Pre-Agents = protocol://[authinfo@]server:port

#	或

#	Pre-Agents = ss://encrypt_method:password@1.2.3.4:8388

**Comment by renzhn** [comment]
你说的前置代理貌似 Polipo 可以很好的满足需求
