### ISSUE TITLE
meow for win服务端会自己挂掉

### ISSUE THREAD

**Issue by niclau** [renzhn/MEOW#2]
运行在azure china的win2012r2 64bit，之前都一直运行正常，但近一星期来会突然挂掉（客户端提示无法与服务端连接）。proxy.exe进程会自己结束。
![qq 20141228170330](https://cloud.githubusercontent.com/assets/575928/5563508/f8d12600-8eb3-11e4-95be-10bdee550169.jpg)
服务端会出现这样N行的错误代码，但我不知该如何复制下来?

**Comment by niclau** [comment]
在debian7上也是会挂~~

**Comment by renzhn** [comment]
@niclau 有日志吗？或者报错什么的

**Comment by niclau** [comment]
终于收集到日志了......貌似是把内存用光了?
![log txt 7z](https://cloud.githubusercontent.com/assets/575928/5988011/606dfbec-a987-11e4-8cbd-9faaa9cf83d4.jpg)

**Comment by renzhn** [comment]
@niclau 可以重现此问题吗？比如上哪个网站什么的。还有网络是ipv6的吗？我自已没遇到这样的错误不好调试

**Comment by niclau** [comment]
@renzhn 我也不知道是什么东西引致，因为不是我一个人用。网络不是IPV6。前几天我看到meow这个进程占用了400多500m内存，但我没管它，然后今天发现，昨天它挂掉了。

**Comment by renzhn** [comment]
@niclau 看来需要做点压力测试啊
你可以先用上游的试试，看有没有问题 https://github.com/cyfdecyf/cow ，因为我不确定是不是上游的bug

**Comment by renzhn** [comment]
更新了新版本，解决了一个重要的bug，你可以试一下

**Comment by renzhn** [comment]
修正了一个会导致服务端崩溃的bug，你可以再试一下

**Comment by niclau** [comment]
@renzhn 自上次更新以来，运作稳定。
谢谢。
