### ISSUE TITLE
直接识别 .cn 全部直连 不是更简单一点吗

### ISSUE THREAD

**Issue by kxjhlele** [renzhn/MEOW#3]
直接识别 .cn 全部直连 不是更简单一点吗

**Comment by renzhn** [comment]
https://github.com/renzhn/MEOW#%E4%B8%8E-cow-%E7%9B%B8%E6%AF%94%E7%9A%84%E4%BF%AE%E6%94%B9
暂时是这样改的， .cn有点过了

**Comment by kxjhlele** [comment]
我感觉 .cn 域名 没有被墙的，直接直连方便，连 Google.cn 都没有被墙。

**Comment by renzhn** [comment]
这个倒是可以考虑下，不过目前的匹配方式还不差
