### ISSUE TITLE
安装完成配置好后执行mow &报错

### ISSUE THREAD

**Issue by bowenwu** [renzhn/MEOW#39]
[root@CentOS ~]# MEOW &
[1] 51005
-bash: MEOW: command not found

如何解决？

**Comment by iyee** [comment]
1. 检查拼写！
2. root是什么鬼？

**Comment by bowenwu** [comment]
拼写没错啊

**Comment by iyee** [comment]
@bowenwu 改就改全，光记得改帖子忘了改标题了。。

**Comment by bowenwu** [comment]
忘了改了，然而用MOEW还是一样的报错啊

**Comment by renzhn** [comment]
MEOW这么难拼么？？

**Comment by iyee** [comment]
我都不知道该说什么好了。。

**Comment by boweic** [comment]
我也碰到了这个问题，MEOW: command not found

是装在自己的 MAC 上的
