### ISSUE TITLE
帮忙看看对 cow 的使用 是否正确,  谢谢。

### ISSUE THREAD

**Issue by zzp8164** [renzhn/MEOW#4]
http://www.jianshu.com/p/a9c660dc8e46

**Comment by renzhn** [comment]
看起来没问题，你也可以试试MEOW

**Comment by zzp8164** [comment]
好 谢谢

On Sun, Mar 1, 2015 at 7:35 PM, Ren Zhen <notifications@github.com> wrote:

> 看起来没问题，你也可以试试MEOW
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/renzhn/MEOW/issues/4#issuecomment-76593066>.
>



-- 
Best Regards
Shaman (Fengxiang Zhu)
