### ISSUE TITLE
mydrivers.com 网站访问不了

### ISSUE THREAD

**Issue by wsxy162** [renzhn/MEOW#52]
使用自带的名单列表不能访问 mydrivers.com ，这个网站原来在 direct 里，我把它移除出名单还是不能上去，只有移到 proxy 里才能访问。如果直接用 cow 来代理，可以访问。这是什么问题？

**Comment by winteryoung** [comment]
我可以. 估计是 mydrivers.com 把你的 ip 段给屏蔽了

**Comment by wsxy162** [comment]
又试了下，可以访问了，估计也是临时现象。
