### ISSUE TITLE
[feature request] enforce proxy

### ISSUE THREAD

**Issue by gregist** [renzhn/MEOW#7]
Could there be an 'enforce proxy' list? Sometimes I need to connect to a Chinese site via proxy.

**Comment by renzhn** [comment]
That's not very practical, I think.

**Comment by gregist** [comment]
Well, it could be very frustrating sometimes when I am pretty sure connecting to some site via proxy is much faster than direct.

It should be not hard to implement. Maybe I will fock it and add the list myself.

**Comment by renzhn** [comment]
I wonder why you use this proxy, are you Chinese or working in China?
Implementing that is not hard, just load another text file in `directlist.go`'s `initDirectList` and add them to `directList.Domain` map as `domainTypeProxy`, then you are almost there.
I'm very happen to merge if you write it well, or I will implement some time.

**Comment by gregist** [comment]
I am not familiar with Go language so it will probably take some time.

Thanks a lot for your instructions.

**Comment by willin** [comment]
node.js会不会

**Comment by renzhn** [comment]
@willin 你想说什么？

**Comment by willin** [comment]
:sunglasses: 推荐工作

**Comment by renzhn** [comment]
@willin 不是很了解...虽然现学感觉也没问题，但是马上毕业已经签了公司了

**Comment by renzhn** [comment]
由于最近经常遇到DNS把域名解析为国内IP的情况，我下面有时间加入此功能
