### ISSUE TITLE
Google总会被直接添加到directList

### ISSUE THREAD

**Issue by CodeFalling** [renzhn/MEOW#8]
`DIRECT 192.168.1.103:53912 CONNECT www.google.com:443`，
然后`www.google.com`都会直接出现在`directList`中，自始至终也没有成功访问过google。其他网站正常

**Comment by CodeFalling** [comment]
初步判断应该是我DNS的原因，换`114.114.114.114`后正常

**Comment by renzhn** [comment]
是的～我最近也遇到过DNS把被墙域名解析成国内IP的情况，所以我打算加入一个“强制使用代理”列表。

另外，你是通过什么途径了解 MEOW 的？

**Comment by CodeFalling** [comment]
通过Google了解到的
