### ISSUE TITLE
端口设置为10008时，Windows版的设置IE代理端口为4411

### ISSUE THREAD

**Issue by CodeFalling** [renzhn/MEOW#9]
`listen = http://0.0.0.0:10008`
![image](https://cloud.githubusercontent.com/assets/5436704/8698961/8881b25c-2b34-11e5-9611-239189421cf2.png)

**Comment by CodeFalling** [comment]
似乎无论如何修改`rc.txt`，这个菜单的端口都为4411

**Comment by renzhn** [comment]
使用ResourceHacker修改，详见 https://github.com/phuslu/taskbar

**Comment by CodeFalling** [comment]
就是说这个程序是不读取`rc.txt`的？

**Comment by renzhn** [comment]
@CodeFalling 是的，这个跟goagent的一样
